import type { Author, Category, Post, RedirectRecord, StaticPage, Tag } from "@/types/content";

const image = (seed: string, alt: string) => ({ url: "https://images.unsplash.com/" + seed + "?auto=format&fit=crop&w=1600&q=80", width: 1600, height: 900, alt });

export const authors: Author[] = [
  { id: "author-mira", name: "Mira Shah", slug: "mira-shah", email: "mira@example.com", bio: "Mira writes about long-term investing systems, editorial quality, and source-backed financial education.", avatar: image("photo-1494790108377-be9c29b29330", "Portrait of Mira Shah"), jobTitle: "Senior Investing Editor", expertise: ["Index funds", "Retirement planning", "Editorial SEO"], credentials: ["CFA charterholder"], socialLinks: ["https://www.linkedin.com"], website: "https://example.com", status: "active", createdAt: "2026-01-05T00:00:00.000Z", updatedAt: "2026-08-20T00:00:00.000Z" },
  { id: "author-jon", name: "Jon Bell", slug: "jon-bell", email: "jon@example.com", bio: "Jon focuses on technical SEO operations for large publishing teams.", avatar: image("photo-1500648767791-00dcc994a43e", "Portrait of Jon Bell"), jobTitle: "Technical SEO Lead", expertise: ["Crawl optimization", "Schema", "Content architecture"], credentials: [], socialLinks: ["https://www.linkedin.com"], status: "active", createdAt: "2026-02-11T00:00:00.000Z", updatedAt: "2026-08-20T00:00:00.000Z" }
];

export const categories: Category[] = [
  { id: "cat-investing", name: "Investing", slug: "investing", description: "Evidence-based guides for portfolios, index funds, brokerage choices, and long-term planning.", seoTitle: "Investing Guides Built for Long-Term Decisions", metaDescription: "Research-backed investing articles with transparent authorship, sources, and freshness signals.", indexStatus: "index", featuredImage: image("photo-1520607162513-77705c0f0d4a", "Editorial desk with investing research") },
  { id: "cat-retirement", name: "Retirement", slug: "retirement", description: "Clear retirement planning explainers covering accounts, contribution strategy, and tax-aware decisions.", indexStatus: "index", featuredImage: image("photo-1500530855697-b586d89ba3ee", "Notebook and calculator for retirement planning") },
  { id: "cat-seo", name: "Technical SEO", slug: "technical-seo", description: "Operational SEO playbooks for crawl control, internal links, redirects, and structured data.", indexStatus: "index", featuredImage: image("photo-1460925895917-afdab827c52f", "Analytics dashboard on laptop") }
];

export const tags: Tag[] = [
  { id: "tag-index-funds", name: "Index Funds", slug: "index-funds", indexStatus: "noindex" },
  { id: "tag-schema", name: "Schema", slug: "schema", indexStatus: "noindex" },
  { id: "tag-crawl", name: "Crawl Budget", slug: "crawl-budget", indexStatus: "noindex" }
];

export const posts: Post[] = [
  { id: "post-best-index-funds", title: "Best Index Funds for Long-Term Investors", slug: "best-index-funds", excerpt: "A practical framework for comparing broad-market index funds without chasing noise or hidden complexity.", content: `<p>Index funds are usually evaluated on cost, tracking quality, diversification, liquidity, and tax efficiency.</p><h2 id="how-to-compare-index-funds">How to compare index funds</h2><p>Start with the fund objective, then compare expense ratio, tracking difference, holdings, and account fit. See our <a href="/retirement/401k-vs-ira">retirement account comparison</a> when choosing account placement. Technical teams can also review our <a href="/technical-seo/internal-linking-at-scale">internal linking workflow</a>.</p><h3 id="expense-ratio">Expense ratio</h3><p>Small annual costs compound over decades, so cost discipline matters.</p><h2 id="common-mistakes">Common mistakes</h2><p>Avoid judging a diversified fund by a single year of returns.</p>`, featuredImage: image("photo-1554224155-6726b3ff858f", "Investor reviewing diversified fund options"), author: authors[0], reviewer: authors[0], category: categories[0], tags: [tags[0]], status: "published", publishedAt: "2026-07-10T10:00:00.000Z", updatedAt: "2026-08-18T10:00:00.000Z", seoTitle: "Best Index Funds for Long-Term Investors", metaDescription: "Compare index funds by cost, diversification, tracking quality, liquidity, and tax efficiency before investing.", robotsIndex: true, robotsFollow: true, focusKeyword: "best index funds", secondaryKeywords: ["long-term investing", "expense ratio", "portfolio diversification"], schemaType: "BlogPosting", featured: true, editorPick: true, readingTime: 4, wordCount: 820, views: 45210, shares: 844, tableOfContents: [{ id: "how-to-compare-index-funds", text: "How to compare index funds", level: 2 }, { id: "expense-ratio", text: "Expense ratio", level: 3 }, { id: "common-mistakes", text: "Common mistakes", level: 2 }], relatedPosts: ["post-401k-vs-ira", "post-internal-linking"], manualInternalLinks: ["post-401k-vs-ira"], sources: [{ title: "Investor.gov Mutual Funds", url: "https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-funds-etfs", publisher: "SEC" }], references: [], faqs: [{ question: "Are index funds risk-free?", answer: "No. Index funds still carry market risk, even when they are broadly diversified." }], reviewedBy: "Mira Shah", lastReviewedAt: "2026-08-18T10:00:00.000Z", redirectHistory: ["/investing/top-index-funds"], createdAt: "2026-07-01T10:00:00.000Z" },
  { id: "post-401k-vs-ira", title: "401(k) vs IRA: How to Choose the Right Retirement Account", slug: "401k-vs-ira", excerpt: "Understand contribution limits, employer matches, investment menus, and tax treatment before choosing where to save.", content: `<p>A 401(k) and an IRA can both help fund retirement, but they solve different planning problems.</p><h2 id="quick-comparison">Quick comparison</h2><p>Employer match, fees, tax treatment, and access rules usually drive the decision.</p><h2 id="when-to-use-both">When to use both</h2><p>Many savers benefit from using both account types when eligible.</p>`, featuredImage: image("photo-1554224154-26032ffc0d07", "Retirement account comparison notes"), author: authors[0], category: categories[1], tags: [], status: "published", publishedAt: "2026-06-02T09:00:00.000Z", updatedAt: "2026-08-12T09:00:00.000Z", seoTitle: "401(k) vs IRA: Which Retirement Account Fits Best", metaDescription: "Compare 401(k) and IRA accounts by employer match, taxes, contribution limits, fees, and investment flexibility.", robotsIndex: true, robotsFollow: true, focusKeyword: "401k vs IRA", secondaryKeywords: ["retirement account", "employer match"], schemaType: "Article", featured: false, editorPick: true, readingTime: 5, wordCount: 1050, views: 38620, shares: 512, tableOfContents: [{ id: "quick-comparison", text: "Quick comparison", level: 2 }, { id: "when-to-use-both", text: "When to use both", level: 2 }], relatedPosts: ["post-best-index-funds"], manualInternalLinks: ["post-internal-linking"], sources: [{ title: "Retirement Topics", url: "https://www.irs.gov/retirement-plans", publisher: "IRS" }], references: [], faqs: [], redirectHistory: [], createdAt: "2026-05-24T09:00:00.000Z" },
  { id: "post-internal-linking", title: "Internal Linking at Scale Without Turning Content Into Spam", slug: "internal-linking-at-scale", excerpt: "Build a suggestion-first internal linking workflow that improves discovery while keeping editors in control.", content: `<p>Large publications need systematic internal linking, but automation should assist editors rather than inject uncontrolled links.</p><h2 id="link-graph">Build a link graph</h2><p>Track source pages, target pages, anchors, and link type.</p><h2 id="quality-controls">Quality controls</h2><p>Prevent self-links, repeated anchors, and irrelevant suggestions.</p>`, featuredImage: image("photo-1551288049-bebda4e38f71", "Search architecture and link graph dashboard"), author: authors[1], category: categories[2], tags: [tags[1], tags[2]], status: "published", publishedAt: "2026-08-01T11:00:00.000Z", updatedAt: "2026-08-22T11:00:00.000Z", seoTitle: "Internal Linking at Scale for Large SEO Sites", metaDescription: "Create an editorial internal linking engine with suggestions, link graph reporting, and spam prevention controls.", robotsIndex: true, robotsFollow: true, focusKeyword: "internal linking at scale", secondaryKeywords: ["orphan pages", "link graph", "technical SEO"], schemaType: "BlogPosting", featured: true, editorPick: false, readingTime: 6, wordCount: 1240, views: 27440, shares: 389, tableOfContents: [{ id: "link-graph", text: "Build a link graph", level: 2 }, { id: "quality-controls", text: "Quality controls", level: 2 }], relatedPosts: ["post-best-index-funds"], manualInternalLinks: ["post-best-index-funds"], sources: [{ title: "Google Search Essentials", url: "https://developers.google.com/search/docs/essentials", publisher: "Google Search Central" }], references: [], faqs: [], redirectHistory: [], createdAt: "2026-07-21T11:00:00.000Z" }
];

export const staticPages: StaticPage[] = [{ id: "page-editorial-policy", title: "Editorial Policy", slug: "editorial-policy", excerpt: "How our editorial team handles sourcing, updates, corrections, and expert review.", content: "<p>Editors must provide accurate authorship, cite sources when needed, and avoid fake freshness or fabricated credentials.</p>", robotsIndex: true, robotsFollow: true, updatedAt: "2026-08-15T00:00:00.000Z" }];
export const redirects: RedirectRecord[] = [{ id: "redirect-index-funds", sourcePath: "/investing/top-index-funds", destinationPath: "/investing/best-index-funds", statusCode: 301, active: true, createdAt: "2026-08-18T10:00:00.000Z" }];


