import type { Metadata } from "next";
import { seoConfig } from "@/config/seo";
import { absoluteUrl, buildCanonicalUrl, resolveCanonicalUrl, resolveCategoryCanonical, resolveLocationCanonical, resolvePostCanonical } from "@/lib/seo/url";
import type { Author, Category, LocationEntity, Post, StaticPage } from "@/types/content";

function robots(index: boolean, follow: boolean): Metadata["robots"] { return { index, follow, googleBot: { index, follow, "max-image-preview": "large", "max-snippet": -1, "max-video-preview": -1 } }; }
function social(title: string, description: string, canonical: string, type: "website" | "article" | "profile" = "website", image = absoluteUrl(seoConfig.defaultOgImage)): Metadata { return { openGraph: { type, title, description, url: canonical, siteName: seoConfig.siteName, images: [{ url: image, alt: seoConfig.siteName }] }, twitter: { card: "summary_large_image", title, description, images: [image] } }; }
export function generateStaticMetadata(input: { title: string; description: string; path: string; index?: boolean; follow?: boolean }): Metadata { const canonical = buildCanonicalUrl(input.path); return { title: input.title, description: input.description, alternates: { canonical }, robots: robots(input.index ?? true, input.follow ?? true), ...social(input.title, input.description, canonical) }; }
export function generateListingMetadata(input: { title: string; description: string; canonical: string; index?: boolean; follow?: boolean }): Metadata { const canonical = buildCanonicalUrl(input.canonical); return { title: input.title, description: input.description, alternates: { canonical }, robots: robots(input.index ?? true, input.follow ?? true), ...social(input.title, input.description, canonical) }; }
export function generatePostMetadata(post: Post): Metadata { const title = post.seoTitle || post.title; const description = post.metaDescription || post.excerpt || seoConfig.defaultDescription; const canonical = resolvePostCanonical(post); const image = absoluteUrl(post.ogImage?.url || post.featuredImage.url); const ogTitle = post.ogTitle || title; const ogDescription = post.ogDescription || description; return { title, description, alternates: { canonical }, robots: robots(post.robotsIndex, post.robotsFollow), openGraph: { type: "article", title: ogTitle, description: ogDescription, url: canonical, siteName: seoConfig.siteName, images: [{ url: image, alt: post.ogImage?.alt || post.featuredImage.alt }], publishedTime: post.publishedAt, modifiedTime: post.updatedAt, authors: [post.author.name], section: post.category.name, tags: post.tags.map((tag) => tag.name) }, twitter: { card: "summary_large_image", title: post.twitterTitle || ogTitle, description: post.twitterDescription || ogDescription, images: [absoluteUrl(post.twitterImage?.url || post.ogImage?.url || post.featuredImage.url)] } }; }
export function generateCategoryMetadata(category: Category): Metadata { const title = category.seoTitle || category.name; const description = category.metaDescription || category.description || seoConfig.defaultDescription; const canonical = resolveCategoryCanonical(category); return { title, description, alternates: { canonical }, robots: robots(category.indexStatus === "index", true), ...social(title, description, canonical) }; }
export function generateLocationMetadata(location: LocationEntity, hasPosts: boolean): Metadata { const title = location.seoTitle || `${location.name} Local Rankings`; const description = location.metaDescription || location.description || seoConfig.defaultDescription; const canonical = resolveLocationCanonical(location); return { title, description, alternates: { canonical }, robots: robots(location.status === "active" && location.indexStatus === "index" && hasPosts, true), ...social(title, description, canonical) }; }
export function generateAuthorMetadata(author: Author): Metadata { const title = author.name + " Articles"; const canonical = buildCanonicalUrl("/author/" + author.slug); return { title, description: author.bio, alternates: { canonical }, robots: robots(true, true), ...social(title, author.bio, canonical, "profile") }; }
export function generatePageMetadata(page: StaticPage): Metadata { const canonical = resolveCanonicalUrl(page.canonicalUrl, "/" + page.slug); const title = page.seoTitle || page.title; const description = page.metaDescription || page.excerpt || seoConfig.defaultDescription; return { title, description, alternates: { canonical }, robots: robots(page.robotsIndex, page.robotsFollow), ...social(title, description, canonical) }; }
