import { seoConfig } from "@/config/seo";
import { absoluteUrl, resolvePostCanonical } from "@/lib/seo/url";
import type { Author, Post } from "@/types/content";

function compact<T extends Record<string, unknown>>(value: T) { return Object.fromEntries(Object.entries(value).filter(([, entry]) => entry !== undefined && entry !== null && entry !== "")) as T; }
const organizationId = () => seoConfig.siteUrl + "#organization";
const websiteId = () => seoConfig.siteUrl + "#website";
function personEntity(author: Author) { return compact({ "@type": "Person", "@id": absoluteUrl("/author/" + author.slug) + "#person", name: author.name, url: absoluteUrl("/author/" + author.slug), image: author.avatar ? absoluteUrl(author.avatar.url) : undefined, jobTitle: author.jobTitle, knowsAbout: author.expertise }); }
export function organizationSchema() { return compact({ "@context": "https://schema.org", "@type": "Organization", "@id": organizationId(), name: seoConfig.organization.name, url: seoConfig.siteUrl, logo: absoluteUrl(seoConfig.organization.logo), sameAs: seoConfig.organization.sameAs }); }
export function websiteSchema() { return { "@context": "https://schema.org", "@type": "WebSite", "@id": websiteId(), name: seoConfig.siteName, url: seoConfig.siteUrl, publisher: { "@id": organizationId() }, potentialAction: { "@type": "SearchAction", target: seoConfig.siteUrl + "/search?q={search_term_string}", "query-input": "required name=search_term_string" } }; }
export function articleSchema(post: Post) { const canonical = resolvePostCanonical(post); const reviewer = post.reviewer ? personEntity(post.reviewer) : post.reviewedBy ? { "@type": "Person", name: post.reviewedBy } : undefined; return compact({ "@context": "https://schema.org", "@type": post.schemaType, headline: post.title, description: post.excerpt, image: absoluteUrl(post.featuredImage.url), datePublished: post.publishedAt, dateModified: post.updatedAt, dateReviewed: post.lastReviewedAt, author: personEntity(post.author), editor: reviewer, reviewedBy: reviewer, citation: [...post.sources, ...post.references].map((source) => compact({ "@type": "CreativeWork", name: source.title, url: source.url, publisher: source.publisher, dateModified: source.dateAccessed })), publisher: organizationSchema(), mainEntityOfPage: { "@type": "WebPage", "@id": canonical }, url: canonical, keywords: [post.focusKeyword, ...post.secondaryKeywords].filter(Boolean).join(", "), articleSection: post.category.name, wordCount: post.wordCount, timeRequired: `PT${post.readingTime}M` }); }
export function breadcrumbSchema(items: Array<{ name: string; url: string }>) { return { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: items.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.name, item: absoluteUrl(item.url) })) }; }
export function faqSchema(post: Post) { return post.faqs.length ? { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: post.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) } : null; }
export function personSchema(author: Author) { return compact({ "@context": "https://schema.org", ...personEntity(author), sameAs: author.socialLinks }); }
